<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>XGamingRuntime</AssemblyName>
    <RootNamespace>XGamingRuntime</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <NoWarn>CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>$(StarTruckBepInEx)\core\Il2CppInterop.Runtime.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
